package com.alipay.business.common.dal.auto.daointerface;

import com.alipay.business.common.dal.auto.dataobject.IdempotencyKeysDO;
import com.alipay.business.common.dal.auto.dataobject.IdempotencyKeysDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IdempotencyKeysDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotency_keys
     *
     * @mbg.generated Fri Mar 13 01:19:42 AEDT 2026
     */
    long countByExample(IdempotencyKeysDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotency_keys
     *
     * @mbg.generated Fri Mar 13 01:19:42 AEDT 2026
     */
    int deleteByExample(IdempotencyKeysDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotency_keys
     *
     * @mbg.generated Fri Mar 13 01:19:42 AEDT 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotency_keys
     *
     * @mbg.generated Fri Mar 13 01:19:42 AEDT 2026
     */
    int insert(IdempotencyKeysDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotency_keys
     *
     * @mbg.generated Fri Mar 13 01:19:42 AEDT 2026
     */
    int insertSelective(IdempotencyKeysDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotency_keys
     *
     * @mbg.generated Fri Mar 13 01:19:42 AEDT 2026
     */
    List<IdempotencyKeysDO> selectByExample(IdempotencyKeysDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotency_keys
     *
     * @mbg.generated Fri Mar 13 01:19:42 AEDT 2026
     */
    IdempotencyKeysDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotency_keys
     *
     * @mbg.generated Fri Mar 13 01:19:42 AEDT 2026
     */
    int updateByExampleSelective(@Param("row") IdempotencyKeysDO row, @Param("example") IdempotencyKeysDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotency_keys
     *
     * @mbg.generated Fri Mar 13 01:19:42 AEDT 2026
     */
    int updateByExample(@Param("row") IdempotencyKeysDO row, @Param("example") IdempotencyKeysDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotency_keys
     *
     * @mbg.generated Fri Mar 13 01:19:42 AEDT 2026
     */
    int updateByPrimaryKeySelective(IdempotencyKeysDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotency_keys
     *
     * @mbg.generated Fri Mar 13 01:19:42 AEDT 2026
     */
    int updateByPrimaryKey(IdempotencyKeysDO row);
}