package com.alipay.business.common.dal.auto.daointerface;

import com.alipay.business.common.dal.auto.dataobject.QrCodeDO;
import com.alipay.business.common.dal.auto.dataobject.QrCodeDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrCodeDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_code
     *
     * @mbg.generated Sat Apr 25 13:57:36 AEST 2026
     */
    long countByExample(QrCodeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_code
     *
     * @mbg.generated Sat Apr 25 13:57:36 AEST 2026
     */
    int deleteByExample(QrCodeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_code
     *
     * @mbg.generated Sat Apr 25 13:57:36 AEST 2026
     */
    int deleteByPrimaryKey(String qrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_code
     *
     * @mbg.generated Sat Apr 25 13:57:36 AEST 2026
     */
    int insert(QrCodeDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_code
     *
     * @mbg.generated Sat Apr 25 13:57:36 AEST 2026
     */
    int insertSelective(QrCodeDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_code
     *
     * @mbg.generated Sat Apr 25 13:57:36 AEST 2026
     */
    List<QrCodeDO> selectByExample(QrCodeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_code
     *
     * @mbg.generated Sat Apr 25 13:57:36 AEST 2026
     */
    QrCodeDO selectByPrimaryKey(String qrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_code
     *
     * @mbg.generated Sat Apr 25 13:57:36 AEST 2026
     */
    int updateByExampleSelective(@Param("row") QrCodeDO row, @Param("example") QrCodeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_code
     *
     * @mbg.generated Sat Apr 25 13:57:36 AEST 2026
     */
    int updateByExample(@Param("row") QrCodeDO row, @Param("example") QrCodeDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_code
     *
     * @mbg.generated Sat Apr 25 13:57:36 AEST 2026
     */
    int updateByPrimaryKeySelective(QrCodeDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qr_code
     *
     * @mbg.generated Sat Apr 25 13:57:36 AEST 2026
     */
    int updateByPrimaryKey(QrCodeDO row);
}