package com.alipay.business.common.dal.auto.daointerface;

import com.alipay.business.common.dal.auto.dataobject.ReceiptDO;
import com.alipay.business.common.dal.auto.dataobject.ReceiptDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReceiptDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt
     *
     * @mbg.generated Tue Jun 30 19:07:47 AEST 2026
     */
    long countByExample(ReceiptDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt
     *
     * @mbg.generated Tue Jun 30 19:07:47 AEST 2026
     */
    int deleteByExample(ReceiptDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt
     *
     * @mbg.generated Tue Jun 30 19:07:47 AEST 2026
     */
    int deleteByPrimaryKey(Object receiptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt
     *
     * @mbg.generated Tue Jun 30 19:07:47 AEST 2026
     */
    int insert(ReceiptDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt
     *
     * @mbg.generated Tue Jun 30 19:07:47 AEST 2026
     */
    int insertSelective(ReceiptDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt
     *
     * @mbg.generated Tue Jun 30 19:07:47 AEST 2026
     */
    List<ReceiptDO> selectByExample(ReceiptDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt
     *
     * @mbg.generated Tue Jun 30 19:07:47 AEST 2026
     */
    ReceiptDO selectByPrimaryKey(Object receiptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt
     *
     * @mbg.generated Tue Jun 30 19:07:47 AEST 2026
     */
    int updateByExampleSelective(@Param("row") ReceiptDO row, @Param("example") ReceiptDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt
     *
     * @mbg.generated Tue Jun 30 19:07:47 AEST 2026
     */
    int updateByExample(@Param("row") ReceiptDO row, @Param("example") ReceiptDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt
     *
     * @mbg.generated Tue Jun 30 19:07:47 AEST 2026
     */
    int updateByPrimaryKeySelective(ReceiptDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt
     *
     * @mbg.generated Tue Jun 30 19:07:47 AEST 2026
     */
    int updateByPrimaryKey(ReceiptDO row);
}