package com.alipay.business.common.dal.auto.daointerface;

import com.alipay.business.common.dal.auto.dataobject.ReceiptItemDO;
import com.alipay.business.common.dal.auto.dataobject.ReceiptItemDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReceiptItemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt_item
     *
     * @mbg.generated Tue Jun 30 17:00:35 AEST 2026
     */
    long countByExample(ReceiptItemDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt_item
     *
     * @mbg.generated Tue Jun 30 17:00:35 AEST 2026
     */
    int deleteByExample(ReceiptItemDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt_item
     *
     * @mbg.generated Tue Jun 30 17:00:35 AEST 2026
     */
    int deleteByPrimaryKey(Object itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt_item
     *
     * @mbg.generated Tue Jun 30 17:00:35 AEST 2026
     */
    int insert(ReceiptItemDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt_item
     *
     * @mbg.generated Tue Jun 30 17:00:35 AEST 2026
     */
    int insertSelective(ReceiptItemDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt_item
     *
     * @mbg.generated Tue Jun 30 17:00:35 AEST 2026
     */
    List<ReceiptItemDO> selectByExample(ReceiptItemDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt_item
     *
     * @mbg.generated Tue Jun 30 17:00:35 AEST 2026
     */
    ReceiptItemDO selectByPrimaryKey(Object itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt_item
     *
     * @mbg.generated Tue Jun 30 17:00:35 AEST 2026
     */
    int updateByExampleSelective(@Param("row") ReceiptItemDO row, @Param("example") ReceiptItemDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt_item
     *
     * @mbg.generated Tue Jun 30 17:00:35 AEST 2026
     */
    int updateByExample(@Param("row") ReceiptItemDO row, @Param("example") ReceiptItemDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt_item
     *
     * @mbg.generated Tue Jun 30 17:00:35 AEST 2026
     */
    int updateByPrimaryKeySelective(ReceiptItemDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receipt_item
     *
     * @mbg.generated Tue Jun 30 17:00:35 AEST 2026
     */
    int updateByPrimaryKey(ReceiptItemDO row);
}