package com.alipay.business.common.dal.auto.daointerface;

import com.alipay.business.common.dal.auto.dataobject.TransactionReceiptItemRelDO;
import com.alipay.business.common.dal.auto.dataobject.TransactionReceiptItemRelDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TransactionReceiptItemRelDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_receipt_item_rel
     *
     * @mbg.generated Sun Jul 12 18:49:29 AEST 2026
     */
    long countByExample(TransactionReceiptItemRelDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_receipt_item_rel
     *
     * @mbg.generated Sun Jul 12 18:49:29 AEST 2026
     */
    int deleteByExample(TransactionReceiptItemRelDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_receipt_item_rel
     *
     * @mbg.generated Sun Jul 12 18:49:29 AEST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_receipt_item_rel
     *
     * @mbg.generated Sun Jul 12 18:49:29 AEST 2026
     */
    int insert(TransactionReceiptItemRelDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_receipt_item_rel
     *
     * @mbg.generated Sun Jul 12 18:49:29 AEST 2026
     */
    int insertSelective(TransactionReceiptItemRelDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_receipt_item_rel
     *
     * @mbg.generated Sun Jul 12 18:49:29 AEST 2026
     */
    List<TransactionReceiptItemRelDO> selectByExample(TransactionReceiptItemRelDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_receipt_item_rel
     *
     * @mbg.generated Sun Jul 12 18:49:29 AEST 2026
     */
    TransactionReceiptItemRelDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_receipt_item_rel
     *
     * @mbg.generated Sun Jul 12 18:49:29 AEST 2026
     */
    int updateByExampleSelective(@Param("row") TransactionReceiptItemRelDO row, @Param("example") TransactionReceiptItemRelDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_receipt_item_rel
     *
     * @mbg.generated Sun Jul 12 18:49:29 AEST 2026
     */
    int updateByExample(@Param("row") TransactionReceiptItemRelDO row, @Param("example") TransactionReceiptItemRelDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_receipt_item_rel
     *
     * @mbg.generated Sun Jul 12 18:49:29 AEST 2026
     */
    int updateByPrimaryKeySelective(TransactionReceiptItemRelDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_receipt_item_rel
     *
     * @mbg.generated Sun Jul 12 18:49:29 AEST 2026
     */
    int updateByPrimaryKey(TransactionReceiptItemRelDO row);
}