package com.alipay.business.core.model.domain;

import java.math.BigDecimal;
import java.util.Date;

/**
 * @author adam
 * @date 24/4/2026 12:42 AM
 */
public class QrCode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qr_code.qr_id
     *
     * @mbg.generated Sat Apr 25 13:38:20 AEST 2026
     */
    private String qrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qr_code.owner_id
     *
     * @mbg.generated Sat Apr 25 13:38:20 AEST 2026
     */
    private String ownerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qr_code.owner_type
     *
     * @mbg.generated Sat Apr 25 13:38:20 AEST 2026
     */
    private String ownerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qr_code.intent
     *
     * @mbg.generated Sat Apr 25 13:38:20 AEST 2026
     */
    private String intent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qr_code.amount
     *
     * @mbg.generated Sat Apr 25 13:38:20 AEST 2026
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qr_code.currency
     *
     * @mbg.generated Sat Apr 25 13:38:20 AEST 2026
     */
    private String currency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qr_code.status
     *
     * @mbg.generated Sat Apr 25 13:38:20 AEST 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qr_code.signature
     *
     * @mbg.generated Sat Apr 25 13:38:20 AEST 2026
     */
    private String signature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qr_code.expires_at
     *
     * @mbg.generated Sat Apr 25 13:38:20 AEST 2026
     */
    private Date expiresAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qr_code.created_at
     *
     * @mbg.generated Sat Apr 25 13:38:20 AEST 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qr_code.updated_at
     *
     * @mbg.generated Sat Apr 25 13:38:20 AEST 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qr_code.qr_id
     *
     * @return the value of qr_code.qr_id
     *
     * @mbg.generated Sat Apr 25 13:38:20 AEST 2026
     */
    public String getQrId() {
        return qrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qr_code.qr_id
     *
     * @param qrId the value for qr_code.qr_id
     *
     * @mbg.generated Sat Apr 25 13:38:20 AEST 2026
     */
    public void setQrId(String qrId) {
        this.qrId = qrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qr_code.owner_id
     *
     * @return the value of qr_code.owner_id
     *
     * @mbg.generated Sat Apr 25 13:38:20 AEST 2026
     */
    public String getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qr_code.owner_id
     *
     * @param ownerId the value for qr_code.owner_id
     *
     * @mbg.generated Sat Apr 25 13:38:20 AEST 2026
     */
    public void setOwnerId(String ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qr_code.owner_type
     *
     * @return the value of qr_code.owner_type
     *
     * @mbg.generated Sat Apr 25 13:38:20 AEST 2026
     */
    public String getOwnerType() {
        return ownerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qr_code.owner_type
     *
     * @param ownerType the value for qr_code.owner_type
     *
     * @mbg.generated Sat Apr 25 13:38:20 AEST 2026
     */
    public void setOwnerType(String ownerType) {
        this.ownerType = ownerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qr_code.intent
     *
     * @return the value of qr_code.intent
     *
     * @mbg.generated Sat Apr 25 13:38:20 AEST 2026
     */
    public String getIntent() {
        return intent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qr_code.intent
     *
     * @param intent the value for qr_code.intent
     *
     * @mbg.generated Sat Apr 25 13:38:20 AEST 2026
     */
    public void setIntent(String intent) {
        this.intent = intent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qr_code.amount
     *
     * @return the value of qr_code.amount
     *
     * @mbg.generated Sat Apr 25 13:38:20 AEST 2026
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qr_code.amount
     *
     * @param amount the value for qr_code.amount
     *
     * @mbg.generated Sat Apr 25 13:38:20 AEST 2026
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qr_code.currency
     *
     * @return the value of qr_code.currency
     *
     * @mbg.generated Sat Apr 25 13:38:20 AEST 2026
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qr_code.currency
     *
     * @param currency the value for qr_code.currency
     *
     * @mbg.generated Sat Apr 25 13:38:20 AEST 2026
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qr_code.status
     *
     * @return the value of qr_code.status
     *
     * @mbg.generated Sat Apr 25 13:38:20 AEST 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qr_code.status
     *
     * @param status the value for qr_code.status
     *
     * @mbg.generated Sat Apr 25 13:38:20 AEST 2026
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qr_code.signature
     *
     * @return the value of qr_code.signature
     *
     * @mbg.generated Sat Apr 25 13:38:20 AEST 2026
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qr_code.signature
     *
     * @param signature the value for qr_code.signature
     *
     * @mbg.generated Sat Apr 25 13:38:20 AEST 2026
     */
    public void setSignature(String signature) {
        this.signature = signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qr_code.expires_at
     *
     * @return the value of qr_code.expires_at
     *
     * @mbg.generated Sat Apr 25 13:38:20 AEST 2026
     */
    public Date getExpiresAt() {
        return expiresAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qr_code.expires_at
     *
     * @param expiresAt the value for qr_code.expires_at
     *
     * @mbg.generated Sat Apr 25 13:38:20 AEST 2026
     */
    public void setExpiresAt(Date expiresAt) {
        this.expiresAt = expiresAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qr_code.created_at
     *
     * @return the value of qr_code.created_at
     *
     * @mbg.generated Sat Apr 25 13:38:20 AEST 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qr_code.created_at
     *
     * @param createdAt the value for qr_code.created_at
     *
     * @mbg.generated Sat Apr 25 13:38:20 AEST 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qr_code.updated_at
     *
     * @return the value of qr_code.updated_at
     *
     * @mbg.generated Sat Apr 25 13:38:20 AEST 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qr_code.updated_at
     *
     * @param updatedAt the value for qr_code.updated_at
     *
     * @mbg.generated Sat Apr 25 13:38:20 AEST 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}