package com.alipay.business.common.service.facade.item;

import java.math.BigDecimal;
import java.util.Date;

/**
 * @author adam
 * @date 29/6/2026 9:51 PM
 */
public class ReceiptSubItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt_item.item_id
     *
     * @mbg.generated Sun Jun 28 23:40:31 AEST 2026
     */
    private Object itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt_item.receipt_id
     *
     * @mbg.generated Sun Jun 28 23:40:31 AEST 2026
     */
    private Object receiptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt_item.name
     *
     * @mbg.generated Sun Jun 28 23:40:31 AEST 2026
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt_item.quantity
     *
     * @mbg.generated Sun Jun 28 23:40:31 AEST 2026
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt_item.unit_price
     *
     * @mbg.generated Sun Jun 28 23:40:31 AEST 2026
     */
    private BigDecimal unitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt_item.total_price
     *
     * @mbg.generated Sun Jun 28 23:40:31 AEST 2026
     */
    private BigDecimal totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt_item.selected_by
     *
     * @mbg.generated Sun Jun 28 23:40:31 AEST 2026
     */
    private String selectedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt_item.status
     *
     * @mbg.generated Sun Jun 28 23:40:31 AEST 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt_item.created_at
     *
     * @mbg.generated Sun Jun 28 23:40:31 AEST 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt_item.updated_at
     *
     * @mbg.generated Sun Jun 28 23:40:31 AEST 2026
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt_item.qr_reference_id
     *
     * @mbg.generated Sun Jun 28 23:40:31 AEST 2026
     */
    private String qrReferenceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt_item.item_id
     *
     * @return the value of receipt_item.item_id
     *
     * @mbg.generated Sun Jun 28 23:40:31 AEST 2026
     */
    public Object getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt_item.item_id
     *
     * @param itemId the value for receipt_item.item_id
     *
     * @mbg.generated Sun Jun 28 23:40:31 AEST 2026
     */
    public void setItemId(Object itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt_item.receipt_id
     *
     * @return the value of receipt_item.receipt_id
     *
     * @mbg.generated Sun Jun 28 23:40:31 AEST 2026
     */
    public Object getReceiptId() {
        return receiptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt_item.receipt_id
     *
     * @param receiptId the value for receipt_item.receipt_id
     *
     * @mbg.generated Sun Jun 28 23:40:31 AEST 2026
     */
    public void setReceiptId(Object receiptId) {
        this.receiptId = receiptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt_item.name
     *
     * @return the value of receipt_item.name
     *
     * @mbg.generated Sun Jun 28 23:40:31 AEST 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt_item.name
     *
     * @param name the value for receipt_item.name
     *
     * @mbg.generated Sun Jun 28 23:40:31 AEST 2026
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt_item.quantity
     *
     * @return the value of receipt_item.quantity
     *
     * @mbg.generated Sun Jun 28 23:40:31 AEST 2026
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt_item.quantity
     *
     * @param quantity the value for receipt_item.quantity
     *
     * @mbg.generated Sun Jun 28 23:40:31 AEST 2026
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt_item.unit_price
     *
     * @return the value of receipt_item.unit_price
     *
     * @mbg.generated Sun Jun 28 23:40:31 AEST 2026
     */
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt_item.unit_price
     *
     * @param unitPrice the value for receipt_item.unit_price
     *
     * @mbg.generated Sun Jun 28 23:40:31 AEST 2026
     */
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt_item.total_price
     *
     * @return the value of receipt_item.total_price
     *
     * @mbg.generated Sun Jun 28 23:40:31 AEST 2026
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt_item.total_price
     *
     * @param totalPrice the value for receipt_item.total_price
     *
     * @mbg.generated Sun Jun 28 23:40:31 AEST 2026
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt_item.selected_by
     *
     * @return the value of receipt_item.selected_by
     *
     * @mbg.generated Sun Jun 28 23:40:31 AEST 2026
     */
    public String getSelectedBy() {
        return selectedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt_item.selected_by
     *
     * @param selectedBy the value for receipt_item.selected_by
     *
     * @mbg.generated Sun Jun 28 23:40:31 AEST 2026
     */
    public void setSelectedBy(String selectedBy) {
        this.selectedBy = selectedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt_item.status
     *
     * @return the value of receipt_item.status
     *
     * @mbg.generated Sun Jun 28 23:40:31 AEST 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt_item.status
     *
     * @param status the value for receipt_item.status
     *
     * @mbg.generated Sun Jun 28 23:40:31 AEST 2026
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt_item.created_at
     *
     * @return the value of receipt_item.created_at
     *
     * @mbg.generated Sun Jun 28 23:40:31 AEST 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt_item.created_at
     *
     * @param createdAt the value for receipt_item.created_at
     *
     * @mbg.generated Sun Jun 28 23:40:31 AEST 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt_item.updated_at
     *
     * @return the value of receipt_item.updated_at
     *
     * @mbg.generated Sun Jun 28 23:40:31 AEST 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt_item.updated_at
     *
     * @param updatedAt the value for receipt_item.updated_at
     *
     * @mbg.generated Sun Jun 28 23:40:31 AEST 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt_item.qr_reference_id
     *
     * @return the value of receipt_item.qr_reference_id
     *
     * @mbg.generated Sun Jun 28 23:40:31 AEST 2026
     */
    public String getQrReferenceId() {
        return qrReferenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt_item.qr_reference_id
     *
     * @param qrReferenceId the value for receipt_item.qr_reference_id
     *
     * @mbg.generated Sun Jun 28 23:40:31 AEST 2026
     */
    public void setQrReferenceId(String qrReferenceId) {
        this.qrReferenceId = qrReferenceId;
    }
}