package com.alipay.business.common.dal.auto.dataobject;

import java.util.Date;

public class IdempotencyKeysDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idempotency_keys.id
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idempotency_keys.idempotency_key
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    private String idempotencyKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idempotency_keys.user_id
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idempotency_keys.request_hash
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    private String requestHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idempotency_keys.reference_id
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    private String referenceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idempotency_keys.status
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idempotency_keys.error_code
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    private String errorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idempotency_keys.response_snapshot
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    private String responseSnapshot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idempotency_keys.created_at
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idempotency_keys.updated_at
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idempotency_keys.retry_count
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    private Integer retryCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idempotency_keys.locked_until
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    private Date lockedUntil;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idempotency_keys.idempotency_type
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    private String idempotencyType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idempotency_keys.id
     *
     * @return the value of idempotency_keys.id
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idempotency_keys.id
     *
     * @param id the value for idempotency_keys.id
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idempotency_keys.idempotency_key
     *
     * @return the value of idempotency_keys.idempotency_key
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    public String getIdempotencyKey() {
        return idempotencyKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idempotency_keys.idempotency_key
     *
     * @param idempotencyKey the value for idempotency_keys.idempotency_key
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    public void setIdempotencyKey(String idempotencyKey) {
        this.idempotencyKey = idempotencyKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idempotency_keys.user_id
     *
     * @return the value of idempotency_keys.user_id
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idempotency_keys.user_id
     *
     * @param userId the value for idempotency_keys.user_id
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idempotency_keys.request_hash
     *
     * @return the value of idempotency_keys.request_hash
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    public String getRequestHash() {
        return requestHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idempotency_keys.request_hash
     *
     * @param requestHash the value for idempotency_keys.request_hash
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    public void setRequestHash(String requestHash) {
        this.requestHash = requestHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idempotency_keys.reference_id
     *
     * @return the value of idempotency_keys.reference_id
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    public String getReferenceId() {
        return referenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idempotency_keys.reference_id
     *
     * @param referenceId the value for idempotency_keys.reference_id
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    public void setReferenceId(String referenceId) {
        this.referenceId = referenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idempotency_keys.status
     *
     * @return the value of idempotency_keys.status
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idempotency_keys.status
     *
     * @param status the value for idempotency_keys.status
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idempotency_keys.error_code
     *
     * @return the value of idempotency_keys.error_code
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    public String getErrorCode() {
        return errorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idempotency_keys.error_code
     *
     * @param errorCode the value for idempotency_keys.error_code
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idempotency_keys.response_snapshot
     *
     * @return the value of idempotency_keys.response_snapshot
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    public String getResponseSnapshot() {
        return responseSnapshot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idempotency_keys.response_snapshot
     *
     * @param responseSnapshot the value for idempotency_keys.response_snapshot
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    public void setResponseSnapshot(String responseSnapshot) {
        this.responseSnapshot = responseSnapshot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idempotency_keys.created_at
     *
     * @return the value of idempotency_keys.created_at
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idempotency_keys.created_at
     *
     * @param createdAt the value for idempotency_keys.created_at
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idempotency_keys.updated_at
     *
     * @return the value of idempotency_keys.updated_at
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idempotency_keys.updated_at
     *
     * @param updatedAt the value for idempotency_keys.updated_at
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idempotency_keys.retry_count
     *
     * @return the value of idempotency_keys.retry_count
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    public Integer getRetryCount() {
        return retryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idempotency_keys.retry_count
     *
     * @param retryCount the value for idempotency_keys.retry_count
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    public void setRetryCount(Integer retryCount) {
        this.retryCount = retryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idempotency_keys.locked_until
     *
     * @return the value of idempotency_keys.locked_until
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    public Date getLockedUntil() {
        return lockedUntil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idempotency_keys.locked_until
     *
     * @param lockedUntil the value for idempotency_keys.locked_until
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    public void setLockedUntil(Date lockedUntil) {
        this.lockedUntil = lockedUntil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idempotency_keys.idempotency_type
     *
     * @return the value of idempotency_keys.idempotency_type
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    public String getIdempotencyType() {
        return idempotencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idempotency_keys.idempotency_type
     *
     * @param idempotencyType the value for idempotency_keys.idempotency_type
     *
     * @mbg.generated Mon Mar 30 21:37:00 AEDT 2026
     */
    public void setIdempotencyType(String idempotencyType) {
        this.idempotencyType = idempotencyType;
    }
}