package com.alipay.business.common.dal.auto.dataobject;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class IdempotencyKeysDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table idempotency_keys
     *
     * @mbg.generated Sun Mar 08 20:45:11 AEDT 2026
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table idempotency_keys
     *
     * @mbg.generated Sun Mar 08 20:45:11 AEDT 2026
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table idempotency_keys
     *
     * @mbg.generated Sun Mar 08 20:45:11 AEDT 2026
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotency_keys
     *
     * @mbg.generated Sun Mar 08 20:45:11 AEDT 2026
     */
    public IdempotencyKeysDOExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotency_keys
     *
     * @mbg.generated Sun Mar 08 20:45:11 AEDT 2026
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotency_keys
     *
     * @mbg.generated Sun Mar 08 20:45:11 AEDT 2026
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotency_keys
     *
     * @mbg.generated Sun Mar 08 20:45:11 AEDT 2026
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotency_keys
     *
     * @mbg.generated Sun Mar 08 20:45:11 AEDT 2026
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotency_keys
     *
     * @mbg.generated Sun Mar 08 20:45:11 AEDT 2026
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotency_keys
     *
     * @mbg.generated Sun Mar 08 20:45:11 AEDT 2026
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotency_keys
     *
     * @mbg.generated Sun Mar 08 20:45:11 AEDT 2026
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotency_keys
     *
     * @mbg.generated Sun Mar 08 20:45:11 AEDT 2026
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotency_keys
     *
     * @mbg.generated Sun Mar 08 20:45:11 AEDT 2026
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idempotency_keys
     *
     * @mbg.generated Sun Mar 08 20:45:11 AEDT 2026
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table idempotency_keys
     *
     * @mbg.generated Sun Mar 08 20:45:11 AEDT 2026
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdempotencyKeyIsNull() {
            addCriterion("idempotency_key is null");
            return (Criteria) this;
        }

        public Criteria andIdempotencyKeyIsNotNull() {
            addCriterion("idempotency_key is not null");
            return (Criteria) this;
        }

        public Criteria andIdempotencyKeyEqualTo(String value) {
            addCriterion("idempotency_key =", value, "idempotencyKey");
            return (Criteria) this;
        }

        public Criteria andIdempotencyKeyNotEqualTo(String value) {
            addCriterion("idempotency_key <>", value, "idempotencyKey");
            return (Criteria) this;
        }

        public Criteria andIdempotencyKeyGreaterThan(String value) {
            addCriterion("idempotency_key >", value, "idempotencyKey");
            return (Criteria) this;
        }

        public Criteria andIdempotencyKeyGreaterThanOrEqualTo(String value) {
            addCriterion("idempotency_key >=", value, "idempotencyKey");
            return (Criteria) this;
        }

        public Criteria andIdempotencyKeyLessThan(String value) {
            addCriterion("idempotency_key <", value, "idempotencyKey");
            return (Criteria) this;
        }

        public Criteria andIdempotencyKeyLessThanOrEqualTo(String value) {
            addCriterion("idempotency_key <=", value, "idempotencyKey");
            return (Criteria) this;
        }

        public Criteria andIdempotencyKeyLike(String value) {
            addCriterion("idempotency_key like", value, "idempotencyKey");
            return (Criteria) this;
        }

        public Criteria andIdempotencyKeyNotLike(String value) {
            addCriterion("idempotency_key not like", value, "idempotencyKey");
            return (Criteria) this;
        }

        public Criteria andIdempotencyKeyIn(List<String> values) {
            addCriterion("idempotency_key in", values, "idempotencyKey");
            return (Criteria) this;
        }

        public Criteria andIdempotencyKeyNotIn(List<String> values) {
            addCriterion("idempotency_key not in", values, "idempotencyKey");
            return (Criteria) this;
        }

        public Criteria andIdempotencyKeyBetween(String value1, String value2) {
            addCriterion("idempotency_key between", value1, value2, "idempotencyKey");
            return (Criteria) this;
        }

        public Criteria andIdempotencyKeyNotBetween(String value1, String value2) {
            addCriterion("idempotency_key not between", value1, value2, "idempotencyKey");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andRequestHashIsNull() {
            addCriterion("request_hash is null");
            return (Criteria) this;
        }

        public Criteria andRequestHashIsNotNull() {
            addCriterion("request_hash is not null");
            return (Criteria) this;
        }

        public Criteria andRequestHashEqualTo(String value) {
            addCriterion("request_hash =", value, "requestHash");
            return (Criteria) this;
        }

        public Criteria andRequestHashNotEqualTo(String value) {
            addCriterion("request_hash <>", value, "requestHash");
            return (Criteria) this;
        }

        public Criteria andRequestHashGreaterThan(String value) {
            addCriterion("request_hash >", value, "requestHash");
            return (Criteria) this;
        }

        public Criteria andRequestHashGreaterThanOrEqualTo(String value) {
            addCriterion("request_hash >=", value, "requestHash");
            return (Criteria) this;
        }

        public Criteria andRequestHashLessThan(String value) {
            addCriterion("request_hash <", value, "requestHash");
            return (Criteria) this;
        }

        public Criteria andRequestHashLessThanOrEqualTo(String value) {
            addCriterion("request_hash <=", value, "requestHash");
            return (Criteria) this;
        }

        public Criteria andRequestHashLike(String value) {
            addCriterion("request_hash like", value, "requestHash");
            return (Criteria) this;
        }

        public Criteria andRequestHashNotLike(String value) {
            addCriterion("request_hash not like", value, "requestHash");
            return (Criteria) this;
        }

        public Criteria andRequestHashIn(List<String> values) {
            addCriterion("request_hash in", values, "requestHash");
            return (Criteria) this;
        }

        public Criteria andRequestHashNotIn(List<String> values) {
            addCriterion("request_hash not in", values, "requestHash");
            return (Criteria) this;
        }

        public Criteria andRequestHashBetween(String value1, String value2) {
            addCriterion("request_hash between", value1, value2, "requestHash");
            return (Criteria) this;
        }

        public Criteria andRequestHashNotBetween(String value1, String value2) {
            addCriterion("request_hash not between", value1, value2, "requestHash");
            return (Criteria) this;
        }

        public Criteria andTxnIdIsNull() {
            addCriterion("txn_id is null");
            return (Criteria) this;
        }

        public Criteria andTxnIdIsNotNull() {
            addCriterion("txn_id is not null");
            return (Criteria) this;
        }

        public Criteria andTxnIdEqualTo(String value) {
            addCriterion("txn_id =", value, "txnId");
            return (Criteria) this;
        }

        public Criteria andTxnIdNotEqualTo(String value) {
            addCriterion("txn_id <>", value, "txnId");
            return (Criteria) this;
        }

        public Criteria andTxnIdGreaterThan(String value) {
            addCriterion("txn_id >", value, "txnId");
            return (Criteria) this;
        }

        public Criteria andTxnIdGreaterThanOrEqualTo(String value) {
            addCriterion("txn_id >=", value, "txnId");
            return (Criteria) this;
        }

        public Criteria andTxnIdLessThan(String value) {
            addCriterion("txn_id <", value, "txnId");
            return (Criteria) this;
        }

        public Criteria andTxnIdLessThanOrEqualTo(String value) {
            addCriterion("txn_id <=", value, "txnId");
            return (Criteria) this;
        }

        public Criteria andTxnIdLike(String value) {
            addCriterion("txn_id like", value, "txnId");
            return (Criteria) this;
        }

        public Criteria andTxnIdNotLike(String value) {
            addCriterion("txn_id not like", value, "txnId");
            return (Criteria) this;
        }

        public Criteria andTxnIdIn(List<String> values) {
            addCriterion("txn_id in", values, "txnId");
            return (Criteria) this;
        }

        public Criteria andTxnIdNotIn(List<String> values) {
            addCriterion("txn_id not in", values, "txnId");
            return (Criteria) this;
        }

        public Criteria andTxnIdBetween(String value1, String value2) {
            addCriterion("txn_id between", value1, value2, "txnId");
            return (Criteria) this;
        }

        public Criteria andTxnIdNotBetween(String value1, String value2) {
            addCriterion("txn_id not between", value1, value2, "txnId");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andErrorCodeIsNull() {
            addCriterion("error_code is null");
            return (Criteria) this;
        }

        public Criteria andErrorCodeIsNotNull() {
            addCriterion("error_code is not null");
            return (Criteria) this;
        }

        public Criteria andErrorCodeEqualTo(String value) {
            addCriterion("error_code =", value, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeNotEqualTo(String value) {
            addCriterion("error_code <>", value, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeGreaterThan(String value) {
            addCriterion("error_code >", value, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeGreaterThanOrEqualTo(String value) {
            addCriterion("error_code >=", value, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeLessThan(String value) {
            addCriterion("error_code <", value, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeLessThanOrEqualTo(String value) {
            addCriterion("error_code <=", value, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeLike(String value) {
            addCriterion("error_code like", value, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeNotLike(String value) {
            addCriterion("error_code not like", value, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeIn(List<String> values) {
            addCriterion("error_code in", values, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeNotIn(List<String> values) {
            addCriterion("error_code not in", values, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeBetween(String value1, String value2) {
            addCriterion("error_code between", value1, value2, "errorCode");
            return (Criteria) this;
        }

        public Criteria andErrorCodeNotBetween(String value1, String value2) {
            addCriterion("error_code not between", value1, value2, "errorCode");
            return (Criteria) this;
        }

        public Criteria andResponseSnapshotIsNull() {
            addCriterion("response_snapshot is null");
            return (Criteria) this;
        }

        public Criteria andResponseSnapshotIsNotNull() {
            addCriterion("response_snapshot is not null");
            return (Criteria) this;
        }

        public Criteria andResponseSnapshotEqualTo(String value) {
            addCriterion("response_snapshot =", value, "responseSnapshot");
            return (Criteria) this;
        }

        public Criteria andResponseSnapshotNotEqualTo(String value) {
            addCriterion("response_snapshot <>", value, "responseSnapshot");
            return (Criteria) this;
        }

        public Criteria andResponseSnapshotGreaterThan(String value) {
            addCriterion("response_snapshot >", value, "responseSnapshot");
            return (Criteria) this;
        }

        public Criteria andResponseSnapshotGreaterThanOrEqualTo(String value) {
            addCriterion("response_snapshot >=", value, "responseSnapshot");
            return (Criteria) this;
        }

        public Criteria andResponseSnapshotLessThan(String value) {
            addCriterion("response_snapshot <", value, "responseSnapshot");
            return (Criteria) this;
        }

        public Criteria andResponseSnapshotLessThanOrEqualTo(String value) {
            addCriterion("response_snapshot <=", value, "responseSnapshot");
            return (Criteria) this;
        }

        public Criteria andResponseSnapshotLike(String value) {
            addCriterion("response_snapshot like", value, "responseSnapshot");
            return (Criteria) this;
        }

        public Criteria andResponseSnapshotNotLike(String value) {
            addCriterion("response_snapshot not like", value, "responseSnapshot");
            return (Criteria) this;
        }

        public Criteria andResponseSnapshotIn(List<String> values) {
            addCriterion("response_snapshot in", values, "responseSnapshot");
            return (Criteria) this;
        }

        public Criteria andResponseSnapshotNotIn(List<String> values) {
            addCriterion("response_snapshot not in", values, "responseSnapshot");
            return (Criteria) this;
        }

        public Criteria andResponseSnapshotBetween(String value1, String value2) {
            addCriterion("response_snapshot between", value1, value2, "responseSnapshot");
            return (Criteria) this;
        }

        public Criteria andResponseSnapshotNotBetween(String value1, String value2) {
            addCriterion("response_snapshot not between", value1, value2, "responseSnapshot");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table idempotency_keys
     *
     * @mbg.generated do_not_delete_during_merge Sun Mar 08 20:45:11 AEDT 2026
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table idempotency_keys
     *
     * @mbg.generated Sun Mar 08 20:45:11 AEDT 2026
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}