package com.alipay.business.common.dal.auto.dataobject;

import java.math.BigDecimal;
import java.util.Date;

public class ReceiptDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.receipt_id
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    private Object receiptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.user_id
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.object_key
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    private String objectKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.bucket_name
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    private String bucketName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.file_url
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    private String fileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.file_name
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.content_type
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    private String contentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.file_size
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    private Long fileSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.status
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.total_amount
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    private BigDecimal totalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.created_at
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.updated_at
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.reference_id
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    private String referenceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.total_amount_paid
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    private BigDecimal totalAmountPaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receipt.total_tax_amount
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    private BigDecimal totalTaxAmount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.receipt_id
     *
     * @return the value of receipt.receipt_id
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    public Object getReceiptId() {
        return receiptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.receipt_id
     *
     * @param receiptId the value for receipt.receipt_id
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    public void setReceiptId(Object receiptId) {
        this.receiptId = receiptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.user_id
     *
     * @return the value of receipt.user_id
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.user_id
     *
     * @param userId the value for receipt.user_id
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.object_key
     *
     * @return the value of receipt.object_key
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    public String getObjectKey() {
        return objectKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.object_key
     *
     * @param objectKey the value for receipt.object_key
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    public void setObjectKey(String objectKey) {
        this.objectKey = objectKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.bucket_name
     *
     * @return the value of receipt.bucket_name
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    public String getBucketName() {
        return bucketName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.bucket_name
     *
     * @param bucketName the value for receipt.bucket_name
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    public void setBucketName(String bucketName) {
        this.bucketName = bucketName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.file_url
     *
     * @return the value of receipt.file_url
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.file_url
     *
     * @param fileUrl the value for receipt.file_url
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.file_name
     *
     * @return the value of receipt.file_name
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.file_name
     *
     * @param fileName the value for receipt.file_name
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.content_type
     *
     * @return the value of receipt.content_type
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.content_type
     *
     * @param contentType the value for receipt.content_type
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.file_size
     *
     * @return the value of receipt.file_size
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.file_size
     *
     * @param fileSize the value for receipt.file_size
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.status
     *
     * @return the value of receipt.status
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.status
     *
     * @param status the value for receipt.status
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.total_amount
     *
     * @return the value of receipt.total_amount
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.total_amount
     *
     * @param totalAmount the value for receipt.total_amount
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.created_at
     *
     * @return the value of receipt.created_at
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.created_at
     *
     * @param createdAt the value for receipt.created_at
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.updated_at
     *
     * @return the value of receipt.updated_at
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.updated_at
     *
     * @param updatedAt the value for receipt.updated_at
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.reference_id
     *
     * @return the value of receipt.reference_id
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    public String getReferenceId() {
        return referenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.reference_id
     *
     * @param referenceId the value for receipt.reference_id
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    public void setReferenceId(String referenceId) {
        this.referenceId = referenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.total_amount_paid
     *
     * @return the value of receipt.total_amount_paid
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    public BigDecimal getTotalAmountPaid() {
        return totalAmountPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.total_amount_paid
     *
     * @param totalAmountPaid the value for receipt.total_amount_paid
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    public void setTotalAmountPaid(BigDecimal totalAmountPaid) {
        this.totalAmountPaid = totalAmountPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receipt.total_tax_amount
     *
     * @return the value of receipt.total_tax_amount
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    public BigDecimal getTotalTaxAmount() {
        return totalTaxAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receipt.total_tax_amount
     *
     * @param totalTaxAmount the value for receipt.total_tax_amount
     *
     * @mbg.generated Fri Jul 03 22:10:27 AEST 2026
     */
    public void setTotalTaxAmount(BigDecimal totalTaxAmount) {
        this.totalTaxAmount = totalTaxAmount;
    }
}