package com.alipay.business.common.dal.auto.dataobject;

import java.util.Date;

public class TransactionReceiptItemRelDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_receipt_item_rel.id
     *
     * @mbg.generated Sun Jul 12 18:49:29 AEST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_receipt_item_rel.transaction_id
     *
     * @mbg.generated Sun Jul 12 18:49:29 AEST 2026
     */
    private String transactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_receipt_item_rel.receipt_item_id
     *
     * @mbg.generated Sun Jul 12 18:49:29 AEST 2026
     */
    private Object receiptItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_receipt_item_rel.quantity
     *
     * @mbg.generated Sun Jul 12 18:49:29 AEST 2026
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_receipt_item_rel.gmt_created
     *
     * @mbg.generated Sun Jul 12 18:49:29 AEST 2026
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_receipt_item_rel.gmt_modified
     *
     * @mbg.generated Sun Jul 12 18:49:29 AEST 2026
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_receipt_item_rel.id
     *
     * @return the value of transaction_receipt_item_rel.id
     *
     * @mbg.generated Sun Jul 12 18:49:29 AEST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_receipt_item_rel.id
     *
     * @param id the value for transaction_receipt_item_rel.id
     *
     * @mbg.generated Sun Jul 12 18:49:29 AEST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_receipt_item_rel.transaction_id
     *
     * @return the value of transaction_receipt_item_rel.transaction_id
     *
     * @mbg.generated Sun Jul 12 18:49:29 AEST 2026
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_receipt_item_rel.transaction_id
     *
     * @param transactionId the value for transaction_receipt_item_rel.transaction_id
     *
     * @mbg.generated Sun Jul 12 18:49:29 AEST 2026
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_receipt_item_rel.receipt_item_id
     *
     * @return the value of transaction_receipt_item_rel.receipt_item_id
     *
     * @mbg.generated Sun Jul 12 18:49:29 AEST 2026
     */
    public Object getReceiptItemId() {
        return receiptItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_receipt_item_rel.receipt_item_id
     *
     * @param receiptItemId the value for transaction_receipt_item_rel.receipt_item_id
     *
     * @mbg.generated Sun Jul 12 18:49:29 AEST 2026
     */
    public void setReceiptItemId(Object receiptItemId) {
        this.receiptItemId = receiptItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_receipt_item_rel.quantity
     *
     * @return the value of transaction_receipt_item_rel.quantity
     *
     * @mbg.generated Sun Jul 12 18:49:29 AEST 2026
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_receipt_item_rel.quantity
     *
     * @param quantity the value for transaction_receipt_item_rel.quantity
     *
     * @mbg.generated Sun Jul 12 18:49:29 AEST 2026
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_receipt_item_rel.gmt_created
     *
     * @return the value of transaction_receipt_item_rel.gmt_created
     *
     * @mbg.generated Sun Jul 12 18:49:29 AEST 2026
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_receipt_item_rel.gmt_created
     *
     * @param gmtCreated the value for transaction_receipt_item_rel.gmt_created
     *
     * @mbg.generated Sun Jul 12 18:49:29 AEST 2026
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_receipt_item_rel.gmt_modified
     *
     * @return the value of transaction_receipt_item_rel.gmt_modified
     *
     * @mbg.generated Sun Jul 12 18:49:29 AEST 2026
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_receipt_item_rel.gmt_modified
     *
     * @param gmtModified the value for transaction_receipt_item_rel.gmt_modified
     *
     * @mbg.generated Sun Jul 12 18:49:29 AEST 2026
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}