server.address=0.0.0.0
server.port=8880
spring.application.name=business-web
spring.security.user.name=admin
spring.security.user.password=devtest123
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
spring.redis.host=localhost
spring.redis.port=6379
management.endpoint.health.validate-group-membership=false
spring.main.allow-bean-definition-overriding=true
# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/business
spring.datasource.username=adam
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional: Hibernate dialect (Spring Boot can usually infer it)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Optional: Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# MyBatis
mybatis.mapper-locations=classpath*:mapper/custom/*.xml
mybatis.type-aliases-package=com.alipay.business.common.dal.auto.dataobject