server.address=0.0.0.0
server.port=8180
spring.application.name=business-web
spring.security.user.name=admin
spring.security.user.password=devtest123
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
spring.redis.host=localhost
spring.redis.port=6379
management.endpoint.health.validate-group-membership=false
spring.main.allow-bean-definition-overriding=true
# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/wallet
spring.datasource.username=adam
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional: Hibernate dialect (Spring Boot can usually infer it)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Optional: Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# MyBatis
mybatis.mapper-locations=classpath*:mapper/custom/*.xml
mybatis.type-aliases-package=com.alipay.business.common.dal.auto.dataobject


# Tell SOFA RPC which port bolt is listening on and what IP to advertise
com.alipay.sofa.rpc.bolt.port=12202
com.alipay.sofa.rpc.registry.address=nacos://127.0.0.1:8848
com.alipay.sofa.rpc.rest.enable=true
com.alipay.sofa.rpc.rest.port=8343

# Kafka bootstrap server (Docker container runs on localhost)
zookeeper.connect=localhost:2181
# Producer config
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.alipay.business.common.service.facade.event

# Error handling deserializer ? wraps bad messages instead of crashing consumer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=com.alipay.account_center.common.service.facade.event.EcTransactionEvent

spring.kafka.bootstrap-servers=localhost:9094

# to generate : openssl rand -base64 32
transfer.token.secret=5glQpxvmNigVyai167hQ28oFSEhPT0S4Eks5vNVBDmc=

stripe.webhook-secret=ee
# Backend secret key for Stripe Java SDK (server-side only).
# Keep real key in environment: export STRIPE_SECRET_KEY=sk_test_xxx
stripe.secret-key=sk_test_51TDcd1KMGrnObnAYq33jj7AmgcKjPE7u6j8QkUYgAK0Or4IadM7PielZfsFIlnszHnfd3ISRgsQr21AbKBFFktgO00q6dga46D
